# Generated by Django 3.0.4 on 2020-03-20 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0005_auto_20200320_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 12, 17, 1, 827209, tzinfo=utc)),
        ),
    ]
