# Generated by Django 3.0.4 on 2020-03-23 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0011_auto_20200323_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 9, 11, 43, 70788, tzinfo=utc)),
        ),
    ]
