# Generated by Django 3.0.4 on 2020-06-15 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_food', '0018_auto_20200615_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 5, 17, 1, 653915, tzinfo=utc)),
        ),
    ]
